"""Add nullable to category_id in Product

Revision ID: 70ae73cd24fd
Revises: cb2ac84ae491
Create Date: 2023-10-25 14:08:54.477523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70ae73cd24fd'
down_revision: Union[str, None] = 'cb2ac84ae491'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
